name: "EVA-ICS"
description: "Eva ICS addon for Home Assistant"
version: "1.0.101"
slug: "eva_ics"
init: false
url: https://github.com/AlexMKX/hassio_eva_ics/tree/master/eva_ics
watchdog: "tcp://[HOST]:7778"
arch:
  - amd64
services:
  - "mqtt:need"
map:
  - homeassistant_config:rw