# Sample workflow for building and deploying a Sphinx site to GitHub Pages
name: Deploy Sphinx with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install prerequisites
        run: pip install -r requirements.txt
        working-directory: ./doc/source
#      - name: Setup Pages
#        uses: actions/configure-pages@v4
      - name: Build with Sphinx
        run: TZ=UTC make html
        working-directory: ./doc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./doc/build/html

  deploy:
    environment:
      name: Deploy pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
